version: '3.9'
services:
  server:
    build:
      context: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
    ports:
      - '8081:8081'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
