version: '3.9'
services:
  server:
    build:
      context: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
